[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://portfolio-backend-qqxe.onrender.com" 